language: python

python:
    - 2.7

env:
    - PYTHONPATH=.

install: "pip install -r requirements.txt"

services:
    - postgresql

before_script:
    - psql -c 'create database testdb;' -U postgres

script: 
    - "py.test ./tests/"
